# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/fedora-38-arm64"
    config.vm.box_check_update = true

    config.vm.define "exercise-ert"

    config.vm.hostname = "exercise-ert"
    config.vm.network "public_network", type: "dhcp"

    config.vm.synced_folder "shared/", "/vagrant/shared", create: true
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.ssh.username = "vagrant"
    config.ssh.keep_alive = true
    config.ssh.forward_agent = true

    config.vm.provider "parallels" do |prl|
        prl.name = "exercise-ert"
        prl.memory = "4096"
        config.vm.provision "shell" do |sh|
            sh.privileged = false
            sh.inline = <<-SHELL
                python3 -m ensurepip --upgrade --user
            SHELL
        end
        config.vm.provision "ansible" do |ansible|
            ansible.verbose = "vv"
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "provision/playbook.yaml"
            ansible.config_file = "provision/ansible.cfg"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3",
            }
        end
    end
end
